 <div
      id="react_render_container"
      class="HYPE_document"
      style="
        margin: auto;
        position: relative;
        width: 1024px;
        height: 768px;
        overflow: hidden;
      "
    >
    </div>

    <!-- end copy -->

    <!-- text content for search engines: -->

    <div style="display: none" aria-hidden="true">
      <div>back</div>
      <div>beginWork</div>
      <div>completeWork</div>
    </div>
